# Parameters file for Surveillance Bot
datapath: "/data/SDS/"                    # SC3 Datapath
networks: ["1Y", "HA"]                    # select networks, list or str
stations: "*"                             # select stations, list or str
locations: "*"                            # select locations, list or str
channels: ["EX1", "EX2", "EX3", "VEI"]    # Specify SOH channels, currently supported EX[1-3] and VEI
stations_blacklist: ["TEST", "EREA"]      # exclude these stations
networks_blacklist: []                    # exclude these networks
interval: 60               # Perform checks every x seconds
n_track: 120               # wait n_track * intervals before performing an action (i.e. send mail/end highlight status)
timespan: 7                # Check data of the recent x days
verbosity: 0               # verbosity flag
track_changes: True        # tracks all changes since GUI startup by text highlighting (GUI only)
warn_count: False          # show number of warnings and errors in table
dt_thresh: [300, 1800]     # threshold (s) for timing delay colourisation (yellow/red)
html_figures: True         # Create html figure directory and links
reread_parameters: True    # reread parameters file (change parameters on runtime, not for itself/GUI refresh/datapath)

POWBOX:
  pb_ok: 1  # Voltage for PowBox OK
  pb_SOH2: # PowBox channel 2 voltage translations
    -1: {"230V": "PBox under 1V", "12V": "PBox under 1V"}
    1: {"230V": "OK", "12V": "OK"}
    2: {"230V": "OFF", "12V": "OK"}
    3: {"230V": "OK", "12V": "overvoltage"}
    4: {"230V": "OK", "12V": "undervoltage"}
    4.5: {"230V": "OFF", "12V": "overvoltage"}
    5: {"230V": "OFF", "12V": "undervoltage"}
  pb_SOH3: # PowBox channel 3 voltage translations
    -1: {"router": "PBox under 1V", "charger": "PBox under 1V"}
    1: {"router": "OK", "charger": "OK"}
    2: {"router": "OK", "charger": "0 < resets < 3"}
    2.5: {"router": "OK", "charger": "locked"}
    3: {"router": "FAIL", "charger": "OK"}
    4: {"router": "FAIL", "charger": "0 < resets < 3"}
    5: {"router": "FAIL", "charger": "locked"}

# Thresholds for program warnings/voltage classifications
THRESHOLDS:
  pb_thresh: 0.2               # Threshold for PowBox Voltage check +/- (V)
  max_temp: 50                 # max temperature for temperature warning
  low_volt: 12                 # min voltage for low voltage warning
  high_volt: 14.8               # max voltage for over voltage warning
  unclassified: 5              # min voltage samples not classified for warning

# ---------------------------------------- OPTIONAL PARAMETERS ---------------------------------------------------------

# add links to html table with specified key as column and value as relative link, interpretable string parameters:
# nw (e.g. 1Y), st (e.g. GR01A), nwst_id (e.g. 1Y.GR01A)
add_links:
  # for example: slmon: {"URL": "path/{nw}_{st}.html", "text": "link"}
  slmon: {"URL": "../slmon/{nw}_{st}.html", "text": "show"}
  24h-plot: {"URL": "../scheli/{nw}/{st}.png", "text": "plot"}

# E-mail notifications
EMAIL:
  mailserver: "localhost"
  addresses: ["marcel.paffrath@rub.de", "kasper.fischer@rub.de"]  # list of mail addresses for info mails
  sender: "webmaster@geophysik.ruhr-uni-bochum.de" # mail sender

# names for plotting of the above defined parameter "channels" in the same order
channel_names: ["Temperature (°C)", "230V/12V Status (V)", "Router/Charger State (V)", "Logger Voltage (V)"]
# specify y-ticks (and ylims) giving, (ymin, ymax, step) for each of the above channels (0: default)
CHANNEL_TICKS:
  - [-10, 50, 10]
  - [1, 5, 1]
  - [1, 5, 1]
  - [9, 15, 1]

# Factor for channel to SI-units (for plotting)
CHANNEL_UNITS:
  EX1: 1e-6
  EX2: 1e-6
  EX3: 1e-6
  VEI: 1e-3

# Transform channel for plotting, perform arithmetic operations in given order, e.g.: PBox EX1 V to deg C: 20 * x -20
CHANNEL_TRANSFORM:
  EX1:
    - ["*", 20]
    - ["-", 20]